# Request

string waypoints_json

float64 x
float64 y
float64 z
float64 roll
float64 pitch
float64 yaw

---

# Result
bool success
float64[] final_joints
string message

---

# Feedback
int32 current_step
int32 total_steps
float64[] current_joints
